rem cmd /v /c "set GOOS=darwin&&set GOARCH=386&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
cmd /v /c "set GOOS=darwin&&set GOARCH=amd64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=dragonfly&&set GOARCH=amd64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
cmd /v /c "set GOOS=freebsd&&set GOARCH=386&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
cmd /v /c "set GOOS=freebsd&&set GOARCH=amd64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
cmd /v /c "set GOOS=freebsd&&set GOARCH=arm&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
cmd /v /c "set GOOS=linux&&set GOARCH=386&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
cmd /v /c "set GOOS=linux&&set GOARCH=amd64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
cmd /v /c "set GOOS=linux&&set GOARCH=arm&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
cmd /v /c "set GOOS=linux&&set GOARCH=arm64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
cmd /v /c "set GOOS=linux&&set GOARCH=ppc64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
cmd /v /c "set GOOS=linux&&set GOARCH=ppc64le&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=linux&&set GOARCH=mips&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=linux&&set GOARCH=mipsle&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=linux&&set GOARCH=mips64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=linux&&set GOARCH=mips64le&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=linux&&set GOARCH=s390x&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=nacl&&set GOARCH=386&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=nacl&&set GOARCH=amd64p32&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=nacl&&set GOARCH=arm&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=netbsd&&set GOARCH=386&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=netbsd&&set GOARCH=amd64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=netbsd&&set GOARCH=arm&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=openbsd&&set GOARCH=386&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=openbsd&&set GOARCH=amd64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=openbsd&&set GOARCH=arm&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=plan9&&set GOARCH=386&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=plan9&&set GOARCH=amd64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=plan9&&set GOARCH=arm&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
rem cmd /v /c "set GOOS=solaris&&set GOARCH=amd64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!"
cmd /v /c "set GOOS=windows&&set GOARCH=386&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!.exe"
cmd /v /c "set GOOS=windows&&set GOARCH=amd64&&go build -ldflags "-X main.version=v0.0.3" -o bin/pct-!GOOS!-!GOARCH!.exe"
